/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oficina;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author asgar
 */
public class frmPista extends javax.swing.JFrame {

    /**
     * Creates new form frmPista
     */
    public frmPista() {
        initComponents();
    }
    public JLabel getc1(){
        return c1;    
    }
    public JLabel getca1(){
        return ca1;
    }
    public JLabel getm1(){
        return m1;
    }
    public JLabel getjfinal(){
        return jfinal;
    }         
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        c1 = new javax.swing.JLabel();
        ca1 = new javax.swing.JLabel();
        m1 = new javax.swing.JLabel();
        jfinal = new javax.swing.JLabel();
        jfinal1 = new javax.swing.JLabel();
        jfinal2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcarro = new javax.swing.JButton();
        jinicio = new javax.swing.JButton();
        jmoto = new javax.swing.JButton();
        jcaminhao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/CARRO.png"))); // NOI18N

        ca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/caminhao.png"))); // NOI18N

        m1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/MOTO.png"))); // NOI18N

        jfinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/borracharia.png"))); // NOI18N

        jfinal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/borracharia.png"))); // NOI18N

        jfinal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/borracharia.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(c1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfinal2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ca1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(c1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ca1)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jfinal2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jfinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m1))
                .addContainerGap())
        );

        jfinal2.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setText("RODOVIA 232");

        jcarro.setText("LIGAR CARRO");
        jcarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcarroActionPerformed(evt);
            }
        });

        jinicio.setText("VOLTA AO INICIO");
        jinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinicioActionPerformed(evt);
            }
        });

        jmoto.setText("LIGAR MOTO");
        jmoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmotoActionPerformed(evt);
            }
        });

        jcaminhao.setText("LIGAR CAMINHÃO");
        jcaminhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcaminhaoActionPerformed(evt);
            }
        });

        jLabel2.setText(" Eliedson Gomes");

        jLabel3.setText("RA: 1751157-5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jinicio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcarro)
                                .addGap(122, 122, 122)
                                .addComponent(jcaminhao)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmoto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmoto)
                    .addComponent(jcarro)
                    .addComponent(jcaminhao))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addComponent(jinicio))
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcarroActionPerformed
        // TODO add your handling code here:
         c1.setLocation(0,c1.getLocation().y);
        RELATORIO hilo1=new RELATORIO(c1, this);
        hilo1.start();
        
    }//GEN-LAST:event_jcarroActionPerformed

    private void jmotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmotoActionPerformed
        // TODO add your handling code here:
        m1.setLocation(0,m1.getLocation().y);
        RELATORIO hilo2=new RELATORIO(m1, this);
        hilo2.start();
    }//GEN-LAST:event_jmotoActionPerformed

    private void jinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinicioActionPerformed
        // TODO add your handling code here:
        ca1.setLocation(0,ca1.getLocation().y);
        RELATORIO hilo3=new RELATORIO(ca1, this);
        hilo3.stop();
        c1.setLocation(0,c1.getLocation().y);
         RELATORIO hilo1=new RELATORIO(c1, this);
        hilo1.stop();
        m1.setLocation(0,m1.getLocation().y);
        RELATORIO hilo2=new RELATORIO(m1, this);
        hilo2.stop();
       
    }//GEN-LAST:event_jinicioActionPerformed

    private void jcaminhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcaminhaoActionPerformed
        // TODO add your handling code here:
        ca1.setLocation(0,ca1.getLocation().y);
        RELATORIO hilo3=new RELATORIO(ca1, this);
        hilo3.start();
    }//GEN-LAST:event_jcaminhaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmPista().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c1;
    private javax.swing.JLabel ca1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jcaminhao;
    private javax.swing.JButton jcarro;
    private javax.swing.JLabel jfinal;
    private javax.swing.JLabel jfinal1;
    private javax.swing.JLabel jfinal2;
    private javax.swing.JButton jinicio;
    private javax.swing.JButton jmoto;
    private javax.swing.JLabel m1;
    // End of variables declaration//GEN-END:variables
}
